# Hexo 配置文件
## 文档: https://hexo.io/docs/configuration.html
## 开源地址: https://github.com/hexojs/hexo/
## 汉化：该配置文件由酷友@https://www.coolapk.com/u/827277?from=qr 汉化

# 网站
title: ma Blog #网站标题
subtitle: '欢迎来到我的小窝'	#网站小标题
description: 个人博客 #网站描述
keywords: blog,android,win10,linux,hexo
#关键字
author: ma  #网站作者
#语言
language:
    - zh-CN
    - en
timezone: 'Asia/Shanghai'	#时区
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
# 网站地址
## 如果您的网站位于子目录中，则将url设置为“ http://yoursite.com/child”，将根目录设置为'/child/'
#网站地
url: http://blog.mpcloud.top/
root: /
 #网站根目录
#永久链接
permalink: posts/:abbrlink.html
permalink_defaults:			#永久链接默认值
pretty_urls:
  trailing_index: 
  #设置是否可从永久链接中删除尾随的'index.html'
  trailing_html:
  #设置是否可从永久链接中删除尾随的'.html'

# 目录
source_dir: source 	  #资源目录，文件夹内的文件将上传至github中
public_dir: public	  #公共目录，用来存放生产的静态文件
  #tag_dir: tags      	  #标签目录，默认的tags 实际存放路径为source/tags
archive_dir: archives     #档案目录，默认是archives
category_dir: categories  #类别目录，默认是categories 实际存放路径为source/categories
code_dir: downloads/code  #代码目录，默认是downloads/code 
i18n_dir: :lang		  #国际化目录，默认与language一致
# 指定不需要渲染的文件或文件夹，以“,”分开
skip_render: 
porn_dir: 

# 新帖子配置
new_post_name: :title.md # 新帖子的文件名
default_layout: post	# 默认布局模板
titlecase: true 	# 设置是否可将标题转换为标题形式
external_link:		
  enable: false 	# 设置是否在新标签页中打开外部链接
  field: site 		# 应用于整个网站
  exclude: ''		#
filename_case: 0	#文件名大小写
render_drafts: false    #设置是否渲染草稿
post_asset_folder: false #设置是否使用资源文件夹，Hexo将会创建新文章时自动创建一个文件夹
relative_link: true	#设置是否把链接改为与根目录的相对位置
future: false	#设置是否显示未来的文章

# 主页设置
# path: 您的博客索引页面的根路径 （默认=''）
# per_page：每页显示的帖子 （0=禁用分页）
# order_by：按发布顺序 （默认按日期降序排列）
index_generator:	#索引生成器
  path: ''
  per_page: 10
  order_by: -date

# 分类和标签
default_category: uncategorized #设置默认分类方式，默认为未分类

category_map: #设置分类别名


tag_map: #设置标签别名

#  元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
## Hexo 使用Moment.js解析和显示日期
##您可以参照下面的网站自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## 除非在post 中设置，否则使用帖子的日期作为更新日期
updated_option: true	#设置是否启用更新的日期

# Pagination 分页
## 将per_page设置为0以禁用分页
per_page: 5
pagination_dir: page

# 包含/排除文件
## include:/exclude: 选项仅适用于“source/”文件夹
include:
exclude:
ignore:

# Extensions拓展插件配置
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
#theme: materialized
theme: stellar


# Algolia Search API Key
algolia:
  applicationID: 'T5WSZ2DTH2'
  apiKey: '70474ba1d50ae3638032f99b096d6f5e'
  indexName: 'mp'

# local search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# hexo-neat
# md博文压缩
neat_enable: true
# 压缩html（ejs，swig等也属于html格式片段）
neat_html:
  enable: true
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: false #打印日志
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/themes/next/source/js/schemes/*'
    - '**/themes/next/source/js/utils.js'
    - '**/themes/next/source/js/local-search.js'
    - '**/themes/next/source/js/motion.js'
    - '**/themes/next/source/js/algolia-search.js'
    - '**/themes/next/source/js/bookmark.js'
    - '**/themes/next/source/js/next-boot.js'
# 永久链接模块
#crc16 & hex 效果为https://post.zz173.com/posts/66c8.html
#crc16 & dec 效果为https://post.zz173.com/posts/65535.html
#crc32 & hex 效果为https://post.zz173.com/posts/8ddf18fb.html
#crc32 & dec 效果为https://post.zz173.com/posts/1690090958.html
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

# 部署方式
## Docs: https://hexo.io/docs/deployment.html
deploy:
 - type: git
   repo:
    github: git@github.com:3207754367/3207754367.github.io.git,master
    #gitcafe: git@e.coding.net:ctrl007/ctrl007.git,master
# - type: baidu_url_submitter


#baidu_url_submit:
#  count: 5 # 提交最新的链接数
#  host:  # 在百度站长平台中注册的域名,虽然官方推荐要带有 www, 但可以不带.
#  token:  # 你的秘钥,每个人都不一样,获取方法在下面
#  path:  baidu_urls.txt # 文本文档的地址,新链接会保存在此文本文档里

# Aplayer播放器配置
aplayer: 
  enable: true

# 图片懒加载
lazyload:
  enable: true 
  onlypost: true
  loadingImg: https://s1.ax1x.com/2020/04/13/GX0DJ0.gif


# hexo-tag-cloud
#tag_cloud:
#  textFont: Trebuchet MS, Helvetica
#  textColor: '#333'
#  textHeight: 25
#  outlineColor: '#E2E1D1'
#  maxSpeed: 0.1 
